@echo off
echo compiling lah pls wait a bit...
g++ -std=c++17 -Wall -Wextra -static main.cpp common.cpp module1_member.cpp module2_book.cpp module3_loan.cpp module4_fine.cpp -o lms.exe
echo Compilation successful! Starting the programme...
lms.exe
pause